spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/plato
      database: plato

server:
  port: 8080

plato:
  multithreading:
    config:
      executor-service:
        corePoolSize: 4
        maxPoolSize: 4
        queueCapacity: 10
  config:
    workingDirectory: /tmp
    branchConsistencyEmailSubject: "Plato :: Branch Consistency Report - {{branch1}} and {{branch2}} branch"
    profileConsistencyEmailSubject: "Plato :: Profile Consistency Report - {{branch}} branch"
    customValidationEmailSubject: "Plato :: Custom Validation Report"
    emailFrom: "username@email.com"

  properties:
    altered:
      values:
        custom-manager:
          - github.config
    suppressed:
      values:
        custom-manager:
          dev:
            - github.config
        role-manager:
          common:
            - github.config
